Project - Portfolio Setup and Mobile Version Skeleton
sja-thedude/Project-Portfolio-setup-and-mobile-version-skeleton pull request #1
Opened 2021-09-15 14:30 UTC by sja-thedude

- HTML file has been Added
- CSS File has been Added
- Images has been Added
- Readme File has been Updated

2021-09-15 14:54 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
GitHub flow is followed. :heavy_check_mark:
PR has a title and summary. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-15 14:54 UTC, SajjadAhmad14 commented on README.md
> +Additional description about the project and its features.
Please add a description of the project features here. Moreover, please add steps to run the project locally. README should be professional. You may use [this](https://github.com/microverseinc/readme-template) template from Microverse.

2021-09-15 14:54 UTC, SajjadAhmad14 commented on index.html
> +	</header>
Please wrap the logo in a link tag.
Please use font-family for the header section from the design page.
Please align the logo and hamburger menu vertically. Kindly see the screenshot below for reference.
![header](https://user-images.githubusercontent.com/35504149/133456929-41b2e9f7-a89d-4457-a15d-42752d40465f.png)

2021-09-15 14:54 UTC, SajjadAhmad14 commented on index.html
> +          </p>
The paragraph (e.g., "I'm a software ...") should have a p tag.
Please use colors and font-family for about section from the design page.

2021-09-15 22:10 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @sja-thedude , Good job working on some of the changes requested by the previous reviewer 👏🏼 👏🏼 

But,  there are still some which aren't addressed yet.

## Required changes :

- [ ] Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-15 22:10 UTC, safafa commented on index.html
> +</section>
![image](https://user-images.githubusercontent.com/43698511/133516381-3824a600-1b7d-404f-af89-d264d4ebcadd.png)

- [ ] As the previous reviewer suggested. You should use the same font family and colors used in the design. check the Figma template for style information. Respecting the original design is one of the project's requirements as it's an important skill for a front-end developer. 
original design :
![image](https://user-images.githubusercontent.com/43698511/133516035-4b175b16-f286-4a61-944f-cbac162e2ab3.png)
You can use this link to lookup [the font](https://fonts.google.com/)

2021-09-16 09:16 UTC, Mihndim2020 approved these changes
Hi @sja-thedude, 

Good job implementing the changes requested by the previews reviewer!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 09:17 UTC, merged